### ISSUE TITLE
System.InvalidOperationException: 'The connection is already open.'

### ISSUE THREAD

**Issue by dedpichto** [dedpichto/ag.DbData.SqlServer#1]
System.InvalidOperationException: 'The connection is already open.' is raised when trying to call any procedure after ExecuteCommand.

**Comment by dedpichto** [comment]
Fixed

**Comment by ghost** [comment]
Hi @dedpichto, How did you fix it?

**Comment by dedpichto** [comment]
Was
`finally
            {
                if (inTransaction && Connection.State == ConnectionState.Open)
                    Connection.Close();
            }`
Became
`finally
            {
                if (!inTransaction)
                    if (Connection.State == ConnectionState.Open)
                        Connection.Close();
            }`
