### ISSUE TITLE
libarary for MongoDB, MongoDB Atlas

### ISSUE THREAD

**Issue by xuan2261** [dedpichto/ag.DbData.SqlServer#3]
you can write simple library for MongoDB, MongoDB Atlas. Thanks you very much.

**Comment by dedpichto** [comment]
Hi,
Unfortunately, I can't. MongoDB is NoSql database and there is no  - AFAIK - any free, not-payable ADO.NET provider for it.

**Comment by xuan2261** [comment]
> Hi,
> Unfortunately, I can't. MongoDB is NoSql database and there is no - AFAIK - any free, not-payable ADO.NET provider for it.

Thanks you very much.
